
name: Python application tests on multiple OS and Python versions

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.10"]
      fail-fast: false  # Isso permite que outros jobs continuem mesmo se um falhar
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt  # Se você tiver outras dependências
    
    - name: Run tests
      run: |
        python -m pytest test_calculator.py -v